# Generated by Django 5.2.3 on 2025-07-01 23:32

import api_gymstra.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gymstra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='fecha_ingreso',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='fecha_ultimo_dia',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='vecesXsemana',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='clase',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='fecha_pago',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='fecta_vto',
            field=models.DateField(default=api_gymstra.utils.calcularFechaVto),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
