# Generated by Django 5.2.3 on 2025-07-10 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_gymstra', '0003_alter_asistencia_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='id_clase',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='clase',
        ),
        migrations.DeleteModel(
            name='Clase',
        ),
    ]
