# Generated by Django 5.2.3 on 2025-07-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gymstra', '0004_remove_asistencia_id_clase_remove_alumno_clase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='id_administrador',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='id_alumno',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='id_asistencia',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='id_cuota',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='id_ejercicio',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='id_rutina',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='zonamuscular',
            name='id_zona_muscular',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
