# Generated by Django 5.2.3 on 2025-08-09 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gymstra', '0005_alter_administrador_id_administrador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutina',
            name='ejercicio',
        ),
        migrations.RemoveField(
            model_name='rutina',
            name='repeticiones',
        ),
        migrations.RemoveField(
            model_name='rutina',
            name='series',
        ),
        migrations.CreateModel(
            name='RutinaEjercicio',
            fields=[
                ('id_rutina_ejercicio', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('series', models.IntegerField()),
                ('repeticiones', models.IntegerField()),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_gymstra.ejercicio')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_gymstra.rutina')),
            ],
            options={
                'verbose_name': 'RutinaEjercicio',
                'verbose_name_plural': 'RutinasEjercicios',
                'db_table': 'RutinaEjercicio',
            },
        ),
        migrations.AddField(
            model_name='rutina',
            name='ejercicios',
            field=models.ManyToManyField(through='api_gymstra.RutinaEjercicio', to='api_gymstra.ejercicio'),
        ),
    ]
