# Generated by Django 5.2.3 on 2025-08-15 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gymstra', '0006_remove_rutina_ejercicio_remove_rutina_repeticiones_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rutinaejercicio',
            options={'verbose_name': 'Rutina Ejercicio', 'verbose_name_plural': 'Rutinas Ejercicios'},
        ),
        migrations.RemoveField(
            model_name='rutinaejercicio',
            name='repeticiones',
        ),
        migrations.RemoveField(
            model_name='rutinaejercicio',
            name='series',
        ),
        migrations.AlterField(
            model_name='rutina',
            name='id_rutina',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rutinaejercicio',
            name='id_rutina_ejercicio',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rutinaejercicio',
            name='rutina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutina_ejercicios', to='api_gymstra.rutina'),
        ),
        migrations.AlterModelTable(
            name='rutinaejercicio',
            table='Rutina Ejercicio',
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id_serie', models.AutoField(primary_key=True, serialize=False)),
                ('series', models.IntegerField()),
                ('repeticiones', models.IntegerField()),
                ('rutina_ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='api_gymstra.rutinaejercicio')),
            ],
            options={
                'verbose_name': 'Serie',
                'verbose_name_plural': 'Series',
                'db_table': 'Series',
            },
        ),
    ]
