# Generated by Django 5.2.3 on 2025-08-15 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gymstra', '0007_alter_rutinaejercicio_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutinaejercicio',
            name='series',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='rutinaejercicio',
            name='rutina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_gymstra.rutina'),
        ),
        migrations.CreateModel(
            name='Repeticion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('rutina_ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repeticiones', to='api_gymstra.rutinaejercicio')),
            ],
            options={
                'verbose_name': 'Repeticion',
                'verbose_name_plural': 'Repeticiones',
                'db_table': 'Repeticion',
            },
        ),
        migrations.DeleteModel(
            name='Serie',
        ),
    ]
