# Generated by Django 5.2.3 on 2025-08-15 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_gymstra', '0008_rutinaejercicio_series_alter_rutinaejercicio_rutina_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repeticion',
            old_name='valor',
            new_name='repeticiones',
        ),
    ]
