# Generated by Django 5.2.3 on 2025-08-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gymstra', '0009_rename_valor_repeticion_repeticiones'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutinaejercicio',
            name='repeticiones',
            field=models.JSONField(default=1),
        ),
        migrations.DeleteModel(
            name='Repeticion',
        ),
    ]
