# Generated by Django 5.2.3 on 2025-08-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gymstra', '0010_rutinaejercicio_repeticiones_delete_repeticion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutinaejercicio',
            name='repeticiones',
            field=models.JSONField(default=list),
        ),
    ]
